### ISSUE TITLE
[Feature Suggestion] Assign resources as actual resources

### ISSUE THREAD

**Issue by GhostwheelX** [jessev14/resource-dice#5]
Could there be an option to allow us to link consumed resources (features, items, etc) to the resources so that when we activate the feature or item, it automatically rolls the die?

**Comment by jessev14** [comment]
Your ideas are all good and doable, but this module was funded by a commission and unfortunately I don't have the means to develop modules in my free time.

I'm happy to merge a PR if you would like to implement it yourself, or you can reach out to me on Discord `enso#0361` if you'd like to discuss funding these features.
