### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Superchunk77** [jessev14/resource-dice#7]
Can the resource dice for each resource be configurable in a range from 0 up to d20 or even d100?

**Comment by jessev14** [comment]
Most likely, yes.

This module was funded through a commission. I unfortunately don't have the means to implement this change in my spare time.

I'm happy to merge PRs if you'd like to implement the feature yourself. Or you can reach out to me on Discord (`ens0_`) if you'd like to discuss funding the feature.
